AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Template for MinecraftCosmos:
Resources:
  StartStopMinecraft:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: StartStopMinecraft
      Handler: StartStopMinecraft.lambda_handler
      Role: !GetAtt
        - StartStopMinecraftRole
        - Arn
      Code:
        S3Bucket: minecraft-cosmos
        S3Key: lambda/StartStopMinecraft.zip
      Runtime: python3.8
      Timeout: 60
  StartStopMinecraftRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: StartStopMinecraftRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: AmazonSNSFullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'sns:*'
                Resource:
                  - '*'
        - PolicyName: AmazonEC2FullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'ec2:*'
                Resource:
                  - '*'